use_frameworks!

abstract_target 'AppGuardAbstract' do
  platform :ios, '9.0'
  
  pod 'AppGuard', :path => '../'
  pod 'lottie-ios'
  pod 'SwiftLint'
  
  target 'AppGuard_Example' do
  end
  
  target 'AppGuard_Tests' do
    pod 'SwiftDate', '~> 4.5.1'
  end
  
end
