use_frameworks!

abstract_target 'AppGuardAbstract' do
  platform :ios, '9.0'
  
  pod 'AppGuard', :path => '../'
  pod 'AppGuard/FirebaseRemoteConfig', :path => '../'
  pod 'lottie-ios'
  pod 'SwiftLint'
  pod 'Kingfisher'
  pod 'Extra/UIKit'
  
  target 'AppGuard_Example' do
  end
  
  target 'AppGuard_ExampleTests' do
    pod 'SwiftDate', '~> 4.5.1'
  end
  
  target 'AppGuard_ExampleUITests' do
  end
  
end
