use_frameworks!
inhibit_all_warnings!

abstract_target 'AppGuardAbstract' do
  platform :ios, '9.0'
  
  pod 'AppGuard/FirebaseRemoteConfig', :path => '../'
  pod 'lottie-ios'
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 4.10.0'
  pod 'Extra/UIKit', '~> 1.2.0'
  pod 'Extra/CoreAnimation', '~> 1.2.0'
  
  target 'AppGuard_Example' do
  end
  
  target 'AppGuard_ExampleTests' do
    pod 'SwiftDate', '~> 4.5.1'
  end
  
  target 'AppGuard_ExampleUITests' do
  end
  
end
